openapi: 3.0.3
info:
  title: LOG430 - eq6 - Service Trajet
  description: |-
    Ceci est la documentation OpenApi du service Trajet, dans le cadre du laboratoire du cours de LOG430 Architecture logicielle.
    Suivez le lien vers la documentation en ligne pour consulter la documentation.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Lien vers la documentation en ligne
  url: https://log430-eq6.github.io/log430-eq6-openApi/
servers:
  - url: https://portainer.10.194.33.156.nip.io/
tags:
  - name: Base
    description: Interface du service commune à tous les services
  - name: Trajet
    description: Interface du service trajet
paths:
  /trajet:
    post:
      tags:
        - Trajet
      summary: Obtenir un trajet
      description: Obtenir un trajet entre deux adresses et en fournissant un mode de transport
      operationId: getTrajet
      requestBody:
        description: Les adresses entre lesquelles on désire obtenir un trajet ainsi que le mode de transport
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrajetQuery'
        required: true
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrajetArray'
        '400':
          description: Adresse(s) invalide(s)
        '401':
          description: Non autorisé
        '404':
          description: Aucun trajet trouvé
        '504':
          description: Le service externe n'a pas répondu
      security:
        - microservices_auth: []
  /services-disponibles:
    get:
      tags:
        - Trajet
      summary: Obtenir la liste des services externes disponibles
      description: Obtenir la liste des services externes disponibles
      operationId: services-disponibles
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceExterneArray'
        '400':
          description: Adresse(s) invalide(s)
        '401':
          description: Non autorisé
        '404':
          description: Aucun trajet trouvé
        '504':
          description: Le service externe n'a pas répondu
  /monitor:
    get:
      tags:
        - Base
      summary: Vérifier l'état du service et état de charge
      description: Renvoie des informations sur l'usage du CPU par le service dans le but de surveiller la charge du service et de s'assurer de son bon fonctionnement.
      operationId: monitor
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonitorInfo'
        '500':
          description: Le service n'est pas disponible
components:
  schemas:
    TrajetQuery:
      type: object
      properties:
        adresse1:
          type: string
          example: 
        adresse2:
          type: string
          example: 
        mode:
          type: string
          example: auto, bus
        serviceExterne:
          type: string
          example: Here, Bing
          description: L'id du service tel que décrit par /services-disponibles
    Trajet:
      type: object
      properties:
        nom:
          type: string
          example: 97 Mont-Royal
        heureDepart:
          type: number
          example: 1666196380425
        durée:
          type: number
          example: 1380425
    ServiceExterne:
      type: object
      properties:
        nom:
          type: string
          example: Api Here
        id:
          type: string
          example: Here, Bing
    MonitorInfo:
      type: object
      properties:
        cpuLoad:
          type: number
          example: 0.23
          description: La charge du CPU exprimée par un nombre entre 0 et 1
        status:
          type: string
          example: ok
          description: La string 'ok' si le service fonctionne correctement
    ServiceExterneArray:
      type: array
      items: 
        $ref: '#/components/schemas/ServiceExterne'
    TrajetArray:
      type: array
      items: 
        $ref: '#/components/schemas/Trajet'
  requestBodies: {}
  securitySchemes:
    microservices_auth:
      type: http
      description: Le token d'authorisation pour les services
      scheme: bearer
      bearerFormat: "Only the jwt, no 'Bearer '"